grafana/grafana-plugin-sdk-go

dataframe/arrow.go, dataframe/arrow_test.go, transform/transform.go
This fix contains the following changes:
* Refactors `df.UnMarshalArrow`
* Renames `df.UnMarshalArrow` to `df.UnmarshalArrow`
Fixes #19
=> 19 refactor un marshal arrow

dataframe/vector.go, dataframe/vector_bool.go, dataframe/vector_bool_nullable.go, dataframe/vector_float.go, dataframe/vector_float_nullable.go, dataframe/vector_int.go, dataframe/vector_int_nullable.go, dataframe/vector_string.go, dataframe/vector_string_nullable.go, dataframe/vector_time.go, dataframe/vector_time_nullable.go, dataframe/vector_uint.go, dataframe/vector_uint_nullable.go
=> dataframe: method to get underlying type of Vector

dataframe/generic_nullable_vector.go, dataframe/nullable_vector.gen.go
Clean up `generic_nullable_vector.go`
=> Remove build tag and comments

backend/convert_from_protobuf.go, backend/convert_to_protobuf.go
adds JSONData, DecryptedSecureJSONData, Updated properties
=> backend: add missing DataSourceConfig fields in to/from protobuf

data/frame.go, data/frame_test.go
This copies @kylebrandt work in [filter](https://github.com/grafana/grafana-plugin-sdk-go/tree/filter) to master and does my best to get it working....
This will get used in https://github.com/grafana/google-sheets-datasource/pull/33
=> Add frame filter utility function

build/common.go
this is used for restarting the plugin for testing
=> Mage: add plugin reload target

data/sqlutil/sql.go, data/sqlutil/sql_test.go
a data.Notice (of warning severity) is added if the limit met.
=> data/sqlutil: add rowLimit to FrameFromRows

build/common.go
Improve the _debugger_ Mage target in various ways, including documentation.
=> Improve debugger target

backend/datasource/query_type_mux_test.go, backend/resource/httpadapter/handler_test.go
https://goreportcard.com/report/github.com/grafana/grafana-plugin-sdk-go
Later we'll add gofmt check to CI.
=> Fix gofmt problems reported with goreportcard

backend/log/log.go, data/frame.go
https://goreportcard.com/report/github.com/grafana/grafana-plugin-sdk-go#misspell
=> Fix misspell problems reported with goreportcard

backend/grpcplugin/grpc_data.go, backend/grpcplugin/grpc_diagnostics.go, backend/grpcplugin/grpc_resource.go, backend/log/log.go, backend/resource.go, backend/transform.go, build/common.go, experimental/sample.go
Fix [linting issues](https://goreportcard.com/report/github.com/grafana/grafana-plugin-sdk-go#golint).
=> Chore: Fix linting issues

backend/transform.go, build/common.go, data/field_config.go, scripts/configs/revive.toml
=> Enforce stricter code style

data/arrow_column_builders.go
`gofmt -w -s data/arrow_column_builders.go`
=> Fix formatting

data/frame_meta.go
See https://github.com/grafana/grafana/pull/25204
=> Add executed query metadata

backend/convert_from_protobuf.go, backend/diagnostics.go, backend/diagnostics_adapter.go, backend/resource.go
Various fixes to improve Grafana integration point of view.
=> Various fixes to improve Grafana client integration

data/arrow_test.go, data/frame.go
so things can be chained, handy in testing syntax - data.NewFrame(...).SetMeta(...)
=> data: add SetMeta() to Frame

build/common.go, build/types.go
This is useful because some plugins cannot be built statically.
Fixes #
=> Add support for enabling cgo

data/frame.go
Improve language in doc comments, generally making them easier to read.
=> Chore: Improve language in doc comments

build/common.go
Backend Data Sources should be able to run on the same platforms as Grafana. Similar to #221 (Add build for Linux on Arm64).
N/A
Was discussed with @ryantxu on the Community call.
=> Add Linux on ARM build

data/time_series.go
**What this PR does / why we need it**: It's the tiniest of doc comment fixes... Sorry... I swear I do this outside the month of October as well...
=> Chore: fix then/than error

.circleci/config.yml, backend/common.go, backend/convert_from_protobuf_test.go, backend/grpcplugin/serve.go, backend/serve.go, data/sqlutil/sql.go, experimental/rest_client.go
Upgrade to latest build image, and fix linting issues caught by latest golangci-lint.
=> CircleCI: Upgrade build image and fix linting issues

.golangci.toml, data/arrow.go, data/field.go, data/frame.go, data/time_series.go
Enable the gocyclo linter which detects overly complex functions, and refactor code (not changing functionality) to deal with issues raised by the linter.
I think the code becomes less complex and more understandable after this PR :)
**PS:** I can recommend diffing locally in a graphical tool, as the diff isn't as bad as it looks in GitHub. If desirable, I can split into multiple PRs.
=> Chore: Enable gocyclo linter

data/field_config.go, data/frame_meta.go
This matches the frontend changes in: https://github.com/grafana/grafana/pull/29695
=> FieldConfig: add path and description metadata

backend/common.go, backend/convert_to_protobuf.go
Fixes missing UID from [convert_to_protobuf](https://github.com/grafana/grafana-plugin-sdk-go/pull/249#issuecomment-760920006)
Fixes #
=> Set UID in convert_to_protobuf

data/field_config.go, data/field_config_test.go
The wrong values were set for value mappings
=> FieldConfig: fix json settings for ValueMapping

data/converters/converters.go, data/converters/converters_test.go
Add converters to nicely get from json to float64/int64
=> Converters: add standard json conversions

data/frame_meta.go
Sync with existing constants in grafana-data package
=> Add constants for preferred visualization types

backend/convert_from_protobuf_test.go, backend/log.go, data/field.go, data/frame.go, data/frame_json_test.go, data/vector_test.go
=> Minor cleanups

experimental/standalone.go
This will automatically pick an open port and restart the grafana plugin process when running in vscode debugger
=> Debugger: restart process when in debug mode

data/field.go, data/field_type.go, data/field_type_test.go, data/frame_json.go, data/frame_meta.go, data/gen.go, data/generic_nullable_vector.go, data/generic_vector.go, data/nullable_vector.gen.go, data/time_series.go, data/vector.gen.go, data/vector.go
Various cleanups for `data` package:
* alloc removed on field creation
* fix some typos and style issues
* better generated code
=> Various data package cleanups

backend/datasource/manage.go, internal/standalone/standalone.go
=> Auto management with standalone mode

backend/data.go, data/field_config.go, data/field_config_test.go, data/value_mapping.go
The current value mapping field config does not match the frontend.
See:
https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/valueMapping.ts
=> FieldConfig: update the value mapping struct to match the frontend

live/channel.go, live/channel_test.go
More strict rules for channel IDs, will be used by Grafana on Subscribe and on Publish.
=> Live: strict channel validation

data/frame_json.go, data/frame_json_test.go
=> Frame json rename

data/framestruct/converter.go, data/framestruct/converter_test.go
This PR is motivated by a feature request for field-specific value converters: Some APIs return all values as strings but we want the resulting dataframe to have concrete types.
With the creation of options, I also added the ability to declare the 0th column. This is useful for when API responses can't be defines as structs.
=> Add optional configuration to framestruct

data/field.go, data/time_series_test.go
=> Add Field.NullableFloatAt()

data/frame.go, data/frame_meta.go, data/time_series.go, data/time_series_test.go
This reverts commit 2263fe0f3e5e598b278317594ebcce55aba2f0a0.
Based on https://github.com/grafana/grafana/pull/36763#issuecomment-880064230
=> Revert "FrameMeta: Adds IsWideTimeSeries (#375)"

data/sqlutil/frame.go
=> Remove frame name results

backend/gtime/gtime.go, backend/gtime/gtime_test.go
This `gtime` package comes from the main grafana repo but I would like to use it for an external plugin.
Needed for https://github.com/grafana/sqlds/issues/43#issuecomment-919101316
I can remove the package from `grafana/grafana` once this is released.
=> Move gtime package from grafana/grafana

contribute/developer-guide.md
Update the developer guide to reflect how to do the latest release.
Fixes #
=> Update how to generate release notes

data/frame.go, data/frame_test.go
To reduce amount of external code we need to write when trying to pick a field or field index from a frame by field name.
=> Helper funcs to get field by name and find field index

data/frame.go, data/frame_json.go, data/frame_json_test.go
adding this so I can unmarshal [ ...frame ] (data.Frames) from js files in tests.
=> Data: add json marshal/unmarshal to data.Frames type

data/frame_test.go
Updates the existing time series code examples in the Go pkg documentation to be in line with dataplane.
=> Data: (Docs) Update code example to be dataplane compliant

data/field_config.go
trying to better explain what `DisplayNameFromDS` does
=> better comment for field.config.DisplayNameFromDS

data/frame_meta.go
This is just sync of this https://github.com/grafana/grafana/pull/80428. So look there for details.
=> Frame: Add UniqueRowIdFields attribute to frame.meta

data/utils/jsoniter/jsoniter.go
We need it for prometheus converter https://github.com/grafana/grafana/blob/main/pkg/util/converter/prom.go#L203
=> Add SkipAndReturnBytes method to jsoniter package

backend/gtime/gtime_test.go
There is an error in this test, it has started to fail. Since it's not covering any new code, I have removed it.
=> Remove flaky test

backend/gtime/gtime.go
=> Mark duration parsing errors as downstream

data/utils/jsoniter/jsoniter.go
This is a required method for a work in progress performance improvement
=> data: Expose ReadStringAsSlice method in jsoniter

experimental/apis/data/v0alpha1/conversions_test.go
(related to fixing https://github.com/grafana/grafana-plugin-sdk-go/issues/1331)
no functional changes, PR only adds a unit test.
before i change the current behavior, i'd like to capture the current behavior in an unit test.
=> experimental: conversions: add test
