- Makefile
Improve the Makefile to build Go code (by default), dependent on the protobuf source.
> Improve Makefile, to also build Go code

- dataframe/arrow.go
- dataframe/bool_vector.go
- dataframe/float_vector.go
- dataframe/string_vector.go
- dataframe/time_vector.go
- dataframe/vector.go
Add `Append` method to `Vector` interface, since it's required for work in gel-app. Also helps cleaning up some internal code.
> dataframe: Add Append method to Vector interface

- backend/core.go
this resulted in incorrect Interval translation for datasource requests routed through GEL.
> fix: s/Micro/Milli/ in DataQuery protobuf adapter

- dataframe/arrow.go
- dataframe/data_query_error.go
- dataframe/dataframe.go
- dataframe/dataframe_test.go
- dataframe/dataframe_warning.go
It should be possible to return an error from a query along with data.  Since the existing [frontend structure](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/types/datasource.ts#L400) is too strange to use directly, I propose a simpler structure that we can convert.
This should let the backend return data along with an error message -- for example "data truncated" or "could not reach all hosts" etc
> Add error message to dataframe metadata

- backend/log/log.go
- backend/setup.go
The setup function should return a logger that is properly configured... See also:
https://github.com/grafana/google-sheets-datasource/pull/45
Does it make sense to have a global logger set?  Looking at the various implementations there are lots of linds of code devoted to passing around the logger created in main()
> Chore: encourage using the sdk logger, not hclog

- backend/setup.go
rather than encouraging plugins to make a new logger, they can just use `backend.Logger` and it should be setup properly
> Chore: don't create a new logger

- data/frame.go
- data/frame_test.go
- data/sql_test.go
Made example:
Might change:
- StringFieldReplacer to take a FieldType instead of VectorType I think, more consistent with other recent changes.
- Make Method on Frame instead, more consistent with rest of package.
Will change:
- vector language to "Field"
> data/docs: example for Replace

- tools/arrow-inspect/yarn.lock
Upgrade JS dependencies, in order to deal with vulnerabilities. Snyk reported one moderate and one high vulnerability, while `yarn audit` reported 103.
> Chore: Upgrade JS dependencies

- backend/convert_from_protobuf.go
- backend/convert_to_protobuf.go
- backend/data.go
- data/arrow.go
- data/arrow_test.go
- data/conversion_input.go
- data/frame.go
- data/frame_test.go
* Adds `Frames` type which is `[]*Frame`
* Adds `Responses` type which is `map[string]*DataResponse`
* Adds `NewQueryDataResponse(size int)` which returns a `QueryDataResponse` with the Responses property initialized to size
* "MarshalArrow" cleanup:
* Frame:
* MarshalArrow -> *Frame.MarshalArrow
* UnmarshalArrow -> UnmarshalArrowFrame
* Frames:
* FramesToByteSlice -> Frames.MarshalArrow 
* BytesSliceToFrames -> UnmarshalArrowFrames
* Misc comment cleanup
> backend/data: New Types to make things cleaner and misc cleanup

- backend/convert_to_protobuf.go
Typo resulted in panic when dataresponse had an error.
> backend: fix panic in convertToProtobuf QueryDataResponse

- backend/convert_from_protobuf.go
- backend/data.go
so it matches the return type of QueryData
oops.
> data: Change NewQueryDataResponse to return a pointer

- build/common.go
banged my head for a long time while working on a plugin that did not have the executable defined 🤦
> Mage: add warning when executable is not defined

- backend/convert_from_protobuf.go
- backend/data.go
**Remove size argument:**
I just keep doing:
`result := backend.NewQueryDataResponse(0)`
So I regret this.  I doubt sizing the map to query length really matters. If one really cares, they can still make the object and size it (as we done in the protobuf conversion of this PR).
**DataResponse not a pointer:**
I don't see a reason to have this as a pointer. I don't think we want to have meaning for a entry in Responses that has a nil value.
In terms of being able to return `nil` from functions, that isn't the pattern here. DataResponse has an Error property, so one returns a `DataResponse` regardless, even in the case of an error (for case some queries successful, others not). The members are just an error and 2 slices, so the object should not be expensive to pass around as a non-pointer. …
> backend: remove size argument from NewQueryDataResponse

- backend/convert_from_protobuf.go
- backend/convert_to_protobuf.go
- backend/data.go
we added a metadata object to DataResponse -- this makes sense, but it does not (yet) have anywhere to go on the frontend.
I am reluctant to add it now knowing that it does not do anything.  When we do want it (soon) it should likely be something other than `Meta json.RawMessage`
> remove meta from DataResponse

- data/conversion_input_test.go
- data/frame.go
- data/frame_test.go
- data/sqlutil/sql_test.go
It messes up the diff output when testing.
Also it was just a shortcut for StringTable, so the functionality is still there.
> data: remove Frame.String() method

- backend/convert_to_protobuf.go
- backend/data.go
- data/frame.go
Else people have to set in there plugin, and will forget, and kind of a silly line.
For example, our template:
```
// create data frame response
frame := data.NewFrame("response")
```
would need the addition of
```
frame.RefID = query.RefID
```
> backend: Set refId on Frame if refId == ""

- backend/doc.go
- doc.go
Adds package documentation to the root should hopefully co-op better with the go-module is defined in the root.
Adds backend package documentation. Quite hard to describe that package.
> Document root and backend packages

- .github/ISSUE_TEMPLATE/1-bug_report.md
- .github/ISSUE_TEMPLATE/2-enhancement_request.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- SECURITY.md
- contribute/developer-guide.md
- Cleanup readme for now by removing outdated example and linking to contribution and development guides plus adding some nice badges
- Adds issues and PR templates (copy from grafana repo with modifications)
- Adds security policy (copy from grafana repo)
- Adds contributing guideline (copy from grafana repo with modifications)- 
- Adds development guideline
Should tick the boxes [here](https://github.com/grafana/grafana-plugin-sdk-go/community).
> Docs: Basic repository documentation/guides, security policy and issue and PR templates

- build/common.go
- build/types.go
For some projects (oracle) we need to install dependencies and set special environment variables for the build.
This PR suggests a way to support that.  Totally open to any other suggestions!
See:
https://github.com/grafana/oracle-datasource/pull/109/files#diff-f60b2cbec853aa02423c3658f48e4155
> Build: support pre-build callback

- data/frame.go
StringTable is meant for human consumption. This adds a sentence clarifying what that means.
> data: code docs - note on not using StringTable for testing

- data/frame_meta.go
As per @ryantxu in https://github.com/grafana/grafana-plugin-sdk-go/pull/182#discussion_r432726130
> I'm fine either way. We have two options:
> 
> 1. `interface{}`
>    pro: easy to work with, it is run though json serialization directly
>    con: _can_ put in invalid data if the value is not an interface
> 2. `map[string]interface{}`
>    pro: forces an object
>    con: can not use a well typed object in go to specify known properties
> 
> Given the trade offs, I think option 1 is better (but can happily go either way)
While doing this, if we do it, want to make sure FieldConfig Custom should not be the same way? But maybe that has to be an object?
As for an example in the wild, in Grafana cloudwatch there is:
```
expectedFrame.Meta = &data.FrameMeta{
Custom: map[string]interface{}{ …
```
> data: (breaking) FrameMeta change custom property to interface

- build/common.go
Disable cgo when building the back-end components of plugins, so static linking will be employed and plugins are portable to musl based Linux distros (f.ex. Alpine).
For reference, [Tanka](https://github.com/grafana/tanka/blob/master/Makefile#L19) already does this.
Fixes #188.
> Build: Disable cgo

- build/common.go
- build/common_unix.go
- go.mod
Support building on Windows, by only compiling `Debugger` and `ReloadPlugin` functions on non-Windows platforms. In the future we should try to implement them on Windows, finding an alternative to unix.Kill.
I'm also replacing syscall.Kill with unix.Kill, since the former is deprecated.
Fixes #183.
> Build: Support building on Windows

- go.mod
- go.sum
has fix for 386 build issue , for https://github.com/grafana/grafana/issues/25287 when this is tagged and merged into Grafana.
> Update arrow dependency

- .circleci/config.yml
- .golangci.toml
Replace the deprecated scopelint Go linter with its suggested replacement [exportloopref](https://github.com/kyoh86/exportloopref).
Need also to upgrade golangci-lint in CI image to get support for this linter.
> Chore: Replace scopelint with exportloopref

- data/frame_meta.go
Change QueryResultMetaStat to QueryStat
Remove duplicated DisplayName property
Change vistype constant to be shorter and prefix related constants
Changes for https://github.com/grafana/grafana-plugin-sdk-go/pull/191
> misc changes

- data/frame_meta.go
Syncs `FrameMeta` definition with typescript interface and defines `QueryResultMetaStat` type.
> Updates FrameMeta definition

- data/frame_test.go
- data/time_series.go
- data/time_series_field_sort_test.go
- data/time_series_test.go
- data/vector.go
- go.mod
If things are not sorted, than depending on the nature of the data, when it changes the default coloring in a Grafana series graph will change.
This is for issues like https://github.com/grafana/grafana/issues/22937 
This only applies to the single wide frame time series model.
A similar thing will need to be done for Frames to handle the other common time series case of multiple frames, with a Frame each having one time and one value column like https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go/data?tab=doc#example-Frame-TSDBTimeSeriesDifferentTimeIndices 
This is called now when LongToWide to use. In the cited issue (insights metrics), it is actually building a wide frame, so this exported as in that case it will be called without LongToWide.
Also adds the following for …
> data: wide time series frame field sorting

- data/time_series.go
- data/time_series_field_sort_test.go
For the reasons stated in https://github.com/grafana/grafana/pull/26207#issuecomment-656315046 , would like sort order to be able to be order based on the label keys.
This aims to do that, and using these changes with Grafana, the results are now sorting more how I think users would like.
Follow up on https://github.com/grafana/grafana-plugin-sdk-go/pull/198
> data: provide keys for wide frame series field sort

- data/arrow.go
- data/arrow_test.go
- data/frame.go
check the row length inside Frame's MarshalArrow method before building the arrow frame to error instead of panicing.
fixes #203
> data: check field length in MarshalArrow

- README.md
Switch from GoDoc to the new Go.dev site in the README, since it's the replacement.
> Chore: Switch from GoDoc to Go.dev link

- experimental/frame_sorter.go
- experimental/frame_sorter_test.go
Allow sorting Dataframes by field
Mongo db plugin needs to sort by field ( atlas free tier doesn't allow sorting when aggregating )
> dataframe sorter

- data/time_series.go
- data/time_series_test.go
for https://github.com/grafana/grafana/issues/27713
bool columns will become labels instead of being considered a metric.
> data: bool Fields as factor in LongToWide

- .golangci.toml
- data/arrow.go
Enable the following linters:
* dogsled
* asciicheck
* errorlint
* sqlclosecheck
errorlint is pretty cool, since it makes sure you compare against wrapped errors properly.
> Chore: Enable more linters

- backend/framer.go
- data/framer.go
- experimental/golden_response_checker.go
I use / define this `Framer` interface in a few backend datasource plugins and I think it would be nice to have this in one location.
I can see a lot of nice utility functions being built around this that could reduce the code in some of our backend plugins by quite a bit.
> Add simple `Framer` interface

- data/frame.go
- data/frame_test.go
This allows us to use `json.NewDecoder(...)` and `json.Marshal` with `data.Frames`.
I did this for some upcoming cache layer stuff where these dataframes (and possibly other types) are going to have to be encoded/decoded before being shipped off to redis/memcached/whatever.
> feat: allow json.unmarshal and json.marshal for dataframes

- data/frame.go
Fix typos in `Frame` doc comments.
> Frame: Fix typos

- .circleci/config.yml
- .golangci.toml
- backend/convert_from_protobuf_test.go
- build/utils/copy_test.go
- data/frame_test.go
Add thelper linter and upgrade build image. The thelper linter ensures that test helper functions start with a call to `t.Helper`.
> Chore: Add thelper linter

- .github/dependabot.yml
Enable dependabot to upgrade dependencies/GitHub Actions, in the same way as for Grafana.
> Chore: Enable dependabot

- backend/instancemgmt/instance_manager.go
- backend/instancemgmt/instance_manager_test.go
- backend/instancemgmt/locker.go
- backend/instancemgmt/locker_test.go
This PR changes how InstanceManager creates, caches and disposes of datasource instances. 
Fixes https://github.com/grafana/grafana-plugin-sdk-go/issues/248
Changes:
1. I added tests which could clarify the issues reported in bug. Without the changes from this PR this tests should fail. 
2. I put the Dispose and code for checking the value existence in the lock section. To optimize it (99.999...% of calls will be just getting the value from cache and returning to the caller after config check) I implemented the double-check locking.
3. I have replaced simple sync.RWMutex with implementation of named RWMutex, which allow to process instances with different id in parallel without locking.
4. Since I replaced RWMutex with Named RWMutex we starting to have …
> Change how InstanceManager manages instance caching

- build/common.go
Add the build configuration for new new apple machines.
NOTE -- this will require changing the build to go 1.16
This may be premature until we add the same target to grafana core :)
> compile for darwin ARM64 (M1)

- data/frame_json_test.go
- data/vector.go
Currently data.FieldType defaults to `FieldTypeInt8` because that is enum value 0 -- this means you can not use ``json:"type,omitempty"`` 
This PR changes to root value to "unknown" and now supports marshaling both as a pointer and as a value.
Since the internal enum value is not stored anywhere, shifting the values should not make a difference
> marshal data.FieldType to json nicely

- data/field.go
Makes it a bit easier to find out what is wrong.
> Add field name to the panic message about unssuported field type

- backend/json_test.go
- data/frame.go
- data/frame_json.go
- data/frame_json_test.go
Without this copy of `stream.Buffer` we could get bytes in a dirty state when accessing later on. `TestFrameMarshalJSONConcurrent` demonstrates this. Also added similar tests for catch possible problems with DataResponse and QueryDataResponse marshaling in the future (those are marshalled fine at the moment).
Overall performance is comparable:
```
name                     old time/op    new time/op    delta
FrameToJSON-12             26.2µs ± 2%    26.5µs ± 1%      ~     (p=0.481 n=10+10)
FrameMarshalJSONStd-12     59.5µs ± 4%    59.7µs ± 0%      ~     (p=0.237 n=10+8)
name                     old alloc/op   new alloc/op   delta
FrameToJSON-12             2.96kB ± 0%    7.85kB ± 0%  +165.41%  (p=0.000 n=10+9)
FrameMarshalJSONStd-12     7.86kB ± 0% …
```
> Fix concurrent frame marshaling

- backend/data.go
- backend/json.go
- backend/json_test.go
- data/frame.go
- data/frame_json.go
This modifies the json read/write for `QueryDataResponse` to closer match the existing format
See https://github.com/grafana/grafana/pull/32303
> JSON: read/write QueryDataResponse to match existing structure

- backend/datasource/serve.go
- backend/serve.go
- experimental/standalone.go
This will allow running the plugin executable as a standalone gRPC server.  This looks for the address information either in an environment variable or in the command line.
See:
https://github.com/ryantxu/noaa-datasource/pull/1/files
> Server: support standalone grpc server for debugging

- experimental/standalone.go
Fix for #307, don't return an error that we could not read standalone file
> fix standalone runner

- data/frame_meta.go
Chicken / egg issue with standard support for subscribing to a stream after a query.
This adds metadata to the standard header so we can subscribe in the frontend
> Meta: add subscribe header for data frame

- data/frame_json.go
- data/frame_json_test.go
* fix malformed json marshal with schema only and existing entities
* test case to show that we can't unmarshal frame with `data` key before `schema` key (previously caused panic)
* test case to show that data only JSON can't be converted to frame (previously caused panic)
In general I think we should take a closer look at this encoding/decoding because in current form it's not easily portable between languages.
> Fix JSON marshal, add test cases

- backend/json_test.go
- data/field_type.go
- data/frame_json.go
- data/testdata/all_types.golden.json
This fixes an issue where the fronted expects boolean types to be identified as "boolean" not "bool"
> DataFrameJSON: frontend expects "boolean" not "bool" type

- backend/datasource/query_type_mux.go
- backend/resource/httpadapter/response_writer.go
Ref https://github.com/grafana/grafana/issues/33779
There's still a log line left in httpadapter package, but should "never" happen. Longer term we might do something more future proof.
> Chore: Remove debug logs in query type mux

- live/channel.go
- live/channel_test.go
- live/doc.go
- live/scope.go
Looks like with WebSocket output plugin we don't really need to have this scope.
> Live: remove push scope

- proto/backend.proto
This change dose not have any real affect, but makes reading the service definition a bit more natural.
> Protobuf: reorder streaming service definition

- build/common.go
- build/types.go
We would like to allow for a more standard go project layout by moving our `main` package out of `./pkg`. This PR allows setting a custom path to be used when building the binaries instead only allowing `./pkg`
> build: Allow custom package path

- experimental/actions/models.go
- experimental/actions/service.go
We have been working with a private api for a while -- it is not totally ready for prime time, but would be nice to have in a public repo so we can make the raspberry-pi repo public and still support actions.
> Actions: move actions from grafana-edge app to experimental

- data/framestruct/converter.go
- data/framestruct/converter_test.go
- data/framestruct/types.go
When returned as arbitrary maps from an API, results sometimes contain subsets of possible data that we'd like to be part of a single dataframe. In this case, to keep the data aligned, framestruct needs to pad the fields.
example:
```
api response:
[
{
"Thing1": "foo",
"Thing2": 36
},
{
"Thing1": "foo1",
"Thing3": "baz1"
}
]
Dataframe result
| Thing1 | Thing2 | Thing3 |
|--------+--------+--------|
| foo    | 36     | nil    |
| foo1   | nil    | baz1   |
```
To achieve this, there are two main changed:
- Framestruct not converts all values to pointers
- prepend or pad nils as necessary to ensure that fields are always the same length
> Feat: framestruct should nil-pad DataFrame fields

- backend/stream.go
Otherwise code like this is impossible:
```go
status := backend.SubscribeStreamStatusPermissionDenied
if someCondition {
status = backend.SubscribeStreamStatusOK
}
```
> Fix subscribe and publish status types

- data/framestruct/converter.go
When converting maps, sort the keys so the resulting dataframes are created deterministically.
Fixes #348
> Ensure stable key order when iterating maps.

- build/common.go
- build/types.go
When building an app plugin with the Go package in the root folder and
the datasource in `src/datasources/somesource` it becomes necessary to
output the binary to `dist/datasources/somesource`.
> build: allow custom output path

- backend/httpclient/provider.go
- backend/httpclient/provider_test.go
Fixes a problem where middlewares from provider was not propagated when creating client/transport.
Used by https://github.com/grafana/grafana/pull/33439
Fixes #
> HTTP Client: Fix provider middleware not forwarded to client

- backend/convert_from_protobuf.go
- backend/convert_to_protobuf.go
- backend/stream.go
- backend/stream_adapter.go
- internal/automanagement/manager.go
Should remove the need to marshal Frame into JSON manually before sending. Uses latest refactoring of Frame JSON conversion added in #355 .
> Refactor Stream send API

- backend/convert_from_protobuf.go
- backend/convert_to_protobuf.go
- backend/stream.go
- backend/stream_adapter.go
- data/frame.go
- data/frame_json.go
- data/frame_json_test.go
- internal/automanagement/manager.go
This will restructure the json encoding to return an object with independent access to schema+data bytes.
This is required so that streaming can easily check if the schema has changed without needing to encode/decode the schema independently.  See: https://github.com/grafana/grafana/pull/34548
This also updates function signature to take an enum rather than set of boolean flags:
> JSON: add a json structure with both data and schema

- backend/stream.go
- data/frame_json.go
- data/frame_json_test.go
This changes the API (again!) to accept an argument on `FrameToJSON` and return bytes directly:
```
data.FrameToJSON(frame, include)
```
This moves the cache version to FrameJSONCache and removes the set functions
> FrameJSON: only use the cache when it is needed as a cache

- data/frame.go
- data/frame_meta.go
- data/time_series.go
- data/time_series_test.go
As part of fixing wide data frame related issues for older plugins, this PR will add `TimeSeriesType` to the `DataFrame` `Meta` object. Next steps are to use this new meta field in the frontend so we can better identify wide data frames in `toLegacyResponseData`:
https://github.com/grafana/grafana/blob/503c3b8f66343f4bc49e0985081c810764f18b66/packages/grafana-data/src/dataframe/processDataFrame.ts#L320
Relates #https://github.com/grafana/grafana/issues/35599
> FrameMeta: Adds IsWideTimeSeries

- build/common.go
- internal/standalone/standalone.go
- internal/utils.go
The current build scripts expect the executable to be in the root, but with app plugins the executable will be in a sub-folder.  This PR checks for an additional "src/datasource/plugin.json" when finding the executable name.
This also move the executable check to an internal utility function so the standalone mode and build can both use it
> Build: support building app datasources (in sub-folder)

- backend/common.go
- backend/common_test.go
- backend/http_settings.go
The mapping of basic auth settings from DataSourceInstanceSettings to HTTPClientOptions was not done properly since all settings was only read from JSONData where basic auth fields are stored on the DataSourceInstanceSettings itself.
Related to https://github.com/grafana/grafana/pull/35798
> Fix mapping of basic auth settings for DataSourceInstanceSettings

- data/sqlutil/converter.go
- data/sqlutil/converter_test.go
Nullable bool aren't handled by SQLUtil.
Fixes #368
This problem was found when developing the Redshift data source. It's temporary solved by providing a custom converter in the plugin. However, external plugins shouldn't have to provide default converters IMO.
> SQLUtil: Add default converter for nullable bool

- backend/stream.go
When subscribing to a channel we may want to send an initial packet that is not a DataFrame
> Streaming: allow raw byte[] for initial data

- backend/common.go
- backend/common_test.go
- backend/http_settings.go
- backend/http_settings_test.go
This should get HTTP client options mapping in the SDK in pair with datasource_cache.go (the old way for core data sources in Grafana).
This change adds data source labels for name and UID as can be seen in [datasource_cache.go](https://github.com/grafana/grafana/blob/bb1dac3c7201e1a8b3bc7def7fdc355c1830623a/pkg/models/datasource_cache.go#L101-L104).
This change adds JSON data to custom options as can be seen in [datasource_cache.go](https://github.com/grafana/grafana/blob/bb1dac3c7201e1a8b3bc7def7fdc355c1830623a/pkg/models/datasource_cache.go#L108-L110). Can be retrieved via `backend.JSONDataFromHTTPClientOptions`.
This change also adds secure JSON data to custom options. Can be retrieved via `backend.SecureJSONDataFromHTTPClientOptions`.
Adding …
> Extends HTTP client options mapping with labels and custom options

- .drone.yml
- Magefile.go
This prevents malicious modifications of the configuration in public repos
See https://github.com/grafana/deployment_tools/blob/master/docs/infrastructure/drone/signing.md for more info
> Sign the Drone config

- backend/http_settings.go
`TLSSkipVerify` should be treated independently of the other TLS options - currently it will only be set and used when either `TLSClientAuth` or `TLSAuthWithCACert` fields are set
Fixes 
https://github.com/grafana/grafana/issues/37177
https://github.com/grafana/grafana/issues/37683
> Allow TLS skip verify to be used on its own

- data/frame_meta.go
- data/frame_type.go
- data/time_series.go
- data/time_series_test.go
Alternative approach started in #375 -- rather than a flag "isWideTimeSeries" this adds a type field to meta so we could define other types also.
This is a baby step that just adds a type property in meta, we will still need to:
1. define the types formally and externally
2. be able to validate types
Initial discussion of types exists in:
https://docs.google.com/document/d/17m6TSSJnxuQMyzk6OKk6umzGqw4Bz33uyRf5Vqf2c04/edit#
> FrameType: add frame type indication

- data/arrow.go
- data/arrow_test.go
This PR adds a new method `FromArrowRecord`, which converts an Arrow Record into a `data.Frame`. 
Whilst the current data frame API has methods for converting serialised bytes representing an Arrow table into a `data.Frame` there is currently nothing that lets one easily convert a materialised `arrow.Record` into a `data.Frame`.
My use-case is as follows: our project ([InfluxDB IOx](https://github.com/influxdata/influxdb_iox)) exposes an API to its SQL front-end via Arrow Flight. I'm prototyping a [Grafana backend data-source](https://github.com/e-dard/grafana-plugin-sdk-go) for IOx that uses Arrow flight as the protocol between plugin and IOx. Using the Go Flight client means that I have easy access to `array.Record` results from IOx but I couldn't finagle an easy way to get them into …
> Arrow: convert from an Arrow Record to a data Frame

- data/field.go
- data/field_test.go
This returns 0 on nil Field or Field.vector instead of a panic. This makes the method more in line with go's built-in `len()`.
It also makes it so a reader doesn't have to do a nil and length check on a field.
> Data: change Field.Len() to be more like len()

- data/sqlutil/scanrow.go
- data/sqlutil/sql.go
Currently we can't use the scan type returned from the database on a converter.  If we define a converter, it would always override the scan type returned from the database.
This PR allows using the scan type defined by the database, so now setting it on the converter is optional.  Setting it on the converter will override the scan type defined by the database.  This is useful when doing regex matching where the underlying scan type may not always be the same.  For example in SAP Hana:  "Fixed8" data type can return [driver.Decimal or driver.NullDecimal](https://github.com/grafana/saphana-datasource/pull/73/files#diff-ee17992c987df01645f07024591cfd9212594ea65f8d7f7a06446d49523fa7d5R52) as the scan type.
The code was a bit gnarly so cleaned it up a …
> allow using the scan type from the db

- data/sqlutil/scanrow.go
Fixes a bug where scan row isn't providing all the rows
> fix - scan row not providing all rows

- data/frame.go
This changes the documentation to state that there should be no nil entires in frame.Fields `[]*Field`, and same for the (Frames) type.
It also states that making them pointers was a mistake. Maybe this comment should be removed? If it wasn't a mistake, I can no longer see the reason for it (I think I may have been the one to do it, or at least allowed it to happen), so if anyone can see a reason it isn't a mistake - I would appreciate that insight. If it just is mistake, then perhaps someday we can make a change to undo it.
> Data: Document no nil entires in Fields / Frames

- data/field_type.go
slighly a breaking change since a comment said concrete, but in that case it would return FieldTypeUnknown which would generally panic somewhere else
> Data: Update FieldTypeFor to support nullable fields

- data/sqlutil/converter.go
- data/sqlutil/converter_test.go
allows sql.NullX types as valid convertible values
Ref # https://github.com/grafana/support-escalations/issues/4923
Some drivers return these sql types instead of native go types.
> allow sql.NullX types as valid convertable values

- data/frame.go
TypeInfo returns the FrameType and FrameTypeVersion from the frame's metadata
Handy since there are nil checks to be done.
> Data: Add TypeInfo method to Frame

- data/field_config.go
This extends the `DataLink` type with support for the `internal` property, allowing us to easily generate internal data links via the backend.
> Add InternalDataLink type

- data/contract_docs/logs.md
based on the previous discussion at https://github.com/grafana/grafana-plugin-sdk-go/pull/570#discussion_r1112227871 we change the contract to ignore the remaining fields.
> Logs contract: ignore remaining fields

- data/contract_docs/logs.md
(there are two approaches, i created two PRs for the two approaches. this one, and https://github.com/grafana/grafana-plugin-sdk-go/pull/661. we should only merge one of them)
this PR clarifies a corner-case that can happen when finding the `timestamp` and the `message` field.
(please note, both the `severity` and `id` fields are string-fields, so as soon as any of these two is added to the dataframe, we will hit the "two string fields" situation.)
pro: explicit about what happens when more than one string fields exist
con: non backward-compatible (for example, Loki&Elastic dataframes simply make sure the message field is the first string field)
> logs contract: more robust field finding, explicit approach

- data/contract_docs/logs.md
as we are getting nanosecond-support directly in the time-field, there is no need for a separate nanosecond-time-field.
> Logs contract: simpler time-field

- data/frame_meta.go
This will add the field '' to the FrameMeta type. This is linked to the PR I have open on grafana/grafana https://github.com/grafana/grafana/pull/66982.
Fixes #
> FrameMeta: add PreferredVisualizationPluginId field to API

- data/sqlutil/converter.go
Supports https://github.com/grafana/support-escalations/issues/7279
There was a bug when dealing float32 when converting to nullablefloat64 since we were returning the float64 but not a pointer.
This PR addresses that
> SQLUtil IntOrFloatToNullableFloat64 float32 conversion fix

- data/sqlutil/dynamic_frame.go
- data/sqlutil/sql.go
- data/sqlutil/sql_test.go
Since `go1.8` `*sql.Rows` supports multiple result sets. But `grafana-plugin-sdk-go` doesn't take this into.
This PR improved `grafana-plugin-sdk-go` for supporting multiple result sets in `db.QueryContext` result
Some databases (like [YDB](https://ydb.tech)) have stream protocol inside. Because designed for large data sets. This fact determines stream API for getting result from server. Multiple result sets is normal for iterate between result batches
Fixes #
> supported multiple result sets in *sql.Rows result from db.QueryContext

- data/utils/jsoniter/jsoniter.go
- data/utils/jsoniter/jsoniter_test.go
The current helpers return an error from a different iterator!
This is a breaking change (i guess) but seems easier to use and a quick fix
> jsoniter: fix helpers

- data/utils/jsoniter/jsoniter.go
- data/utils/jsoniter/jsoniter_test.go
This PR is just adding necessary functions to the `jsoniter` package.
This was done by https://github.com/grafana/grafana-plugin-sdk-go/pull/841
But unfortunately it was [reverted](https://github.com/grafana/grafana-plugin-sdk-go/pull/878) due to issues: https://raintank-corp.slack.com/archives/CMSUYD6H3/p1706642169777429
So here I am adding only functions and unit tests without changing any logic in existing code. The rest of the changes will be done after merging this PR.
> Chore: Add more functions to jsoniter package

- data/utils/maputil/maputil.go
- data/utils/maputil/maputil_test.go
moving `maputil` from grafana/grafana.
https://github.com/grafana/grafana/blob/025b2f3011821bb7e6ab4781e252f3a1ecd19130/pkg/util/maputil/maputil.go
Also `grafana-azure-sdk-go` [has it](https://github.com/grafana/grafana-azure-sdk-go/tree/main/util/maputil). With this in place azure and future promlib can use it from `grafana-plugin-sdk-go`.
> Introduce maputil

- data/sqlutil/scanrow.go
If the `scanType` value is `nil` (which is possible for certain SQL data types) a panic will be triggered rather than providing the user with a useful error to understand what has gone wrong.
This PR detects this case and returns an error detailing what column has the invalid type.
Related to grafana/grafana#81935
> SQL: Check if `scanType` value is `nil`

- data/sqlutil/macros.go
- data/sqlutil/macros_test.go
Adds default macros for `$__interval`  and `$__interval_ms` so any sqlds-based data source can get it for free.
Fixes https://github.com/grafana/grafana-aws-sdk/issues/44
Will update sqlds after this is merged.
> SQL: Add default interval and interval_ms macros to sqlutil

- data/sqlutil/macros.go
- data/sqlutil/macros_test.go
Applying macros is not deterministic using `sqlutil.Interpolate` if one macro is a substring of another one. E.g. a query such as `select '$__interval', $__interval_ms` could potentially apply the `$__interval` macro in place of `$__interval_ms` and `$__invertal_ms` would not be applied. For example, if `$__interval` evaluates to `"1s"`, then the query would incorrectly be `select '1s', 1s_ms`
Fixes #
> SQL: Apply longer macros before shorter macros

- data/arrow.go
The SDK currently will return a frame as arrow byte array -- this is fine for IPC, however when wanting to work directly with arrow (and convert to parquet!) access to the raw arrow/Table helps a lot.
This PR refactors the current marshal logic to expose the typed response not just `[]byte`
> Arrow: Expose frame to arrow.Table utility function

- data/time_series.go
- data/time_series_test.go
Setting the TypeVersion to greater than [0, 0] (along with Meta.Type being set) indicates that the produced
frame follows the dataplane contract (see https://grafana.com/developers/dataplane/ and https://github.com/grafana/dataplane).
```
wideFrame.Meta.TypeVersion = FrameTypeVersion{0, 1}
```
*Okay, so what will that do?*
From a user perspective, there are no expected changes.
Certain datasources call LongWide (In particular, SQL datasources) when the query type in the UI is set to "time series". This sets the output of that call to be "dataplane compliant".
Two consumers will follow a different code path in this case (Server Side Expressions and Recorded Queries). From a user perspective things should change unless there is a bug in those code …
> Dataplane: Enable dataplane for results of LongToWide

- data/field_type.go
- data/frame_json.go
- data/frame_json_test.go
Currently the first field in values is read into a generic array and then converted to vector.  This fails for JSON fields.
This PR fixes parsing JSON from the first field.
> JSON: Ensure all fields types work as expected when they are the first field in a frame

- data/sqlutil/scanrow.go
While monitoring logs from api server for Athena plugin, we noticed this error: [duplicate column names are not allowed](https://ops.grafana-ops.net/explore?schemaVersion=1&panes=%7B%22hrk%22:%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bservice_name%3D%5C%22grafana%2Fathena-datasource-grafana-app-steady%5C%22%7D%20%7C%3D%20%60duplicate%20column%20names%20are%20not%20allowed%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1)
I think these errors should be marked as downstream since as far as I can see they are a result of a user "error" …
> SQLUtil: Mark errors regarding duplicate column names as downstream

- backend/gtime/gtime.go
> Parse Interval: Mark invalid syntax errors as downstream

- backend/gtime/gtime.go
Realized I missed one more place where the error should be marked as downstream when duration provided is invalid 😔
> Mark invalid duration as downstream error

- data/time_series.go
- data/time_series_errors.go
Follow up/different strategy for https://github.com/grafana/grafana-plugin-sdk-go/pull/1099
This PR exports the errors that we can later check for downstream errors. It also updates errors to make them more understandable for user.
> Export errors for time series processing

- data/sqlutil/sql.go
Making some changes based on some errors being incorrectly marked in the MSSQL data source (that I believe can also be incorrectly marked in Postgres and MySQL also).
The errors that I've modified here are ones that I believe can only error due to downstream issues rather than the plugin. Please let me know if you disagree as I think determining which the ultimate source of an error is quite challenging.
With some follow up PR's to grafana/grafana this would fix some issues we're seeing atm.
If we don't want to mark all of these as downstream then I believe we should at least mark the `rows.Err()` error as downstream.
> SQL: Set relevant errors to downstream

- data/field.go
- data/field_test.go
- data/field_type_enum.go
- data/frame.go
- data/generic_nullable_vector.go
- data/generic_vector.go
- data/nullable_vector.gen.go
- data/vector.gen.go
- data/vector.go
Adds the `NilAt(i int) bool` method to `Field`.
```
// NilAt returns true if the element at index idx of the Field is nil.
// This is useful since the interface returned by At() will not be nil
// even if the underlying element is nil (without an type assertion).
// It will always return false if the Field is not nullable.
// It can panic if idx is out of range.
func (f *Field) NilAt(idx int) bool {
return f.vector.NilAt(idx)
}
```
Fixes #
> data: Add NilAt method to Field and Frame

- data/sqlutil/query.go
- data/sqlutil/query_test.go
This utility is used in SQL data sources to process `backend.DataQuery.JSON` into a query object. If the provided JSON is incorrect, it results in a downstream error, as an invalid query was sent to the data source plugin.
> SQL utils: Fix error source when unmarhsaling invalid query object

- data/sqlutil/converter.go
Export `ErrorUnexpectedTypeConversion` error so we can use it in [isProcessingDownstreamError](https://github.com/grafana/sqlds/blob/main/query.go#L244) to check for this downstream error.
> Export conversion error `ErrorUnexpectedTypeConversion`

- backend/gtime/gtime.go
- backend/gtime/gtime_bench_test.go
- backend/gtime/gtime_test.go
`ParseIntervalStringToTimeDuration` method is used in `prometheus`, `loki` and `cloud-monitoring` data sources. `loki` and `prometheus` rely on it for all query request. Improving it's performance resulted a huge gain. See the comparison below. 
This method is using when we get the request and parse the request data into a model. Its overall impact to memory consumption is small comparing to the other parts. But considering that it's been used in many places total impact is still important. 
Also I improved it in all areas that means, less allocations, less gc overheat, faster calculations.
```
❯ benchstat pmem.0.txt pmem.4.txt …
```
> backend: improve ParseIntervalStringToTimeDuration method performance in gtime package by ~93%

- data/time_series.go
- data/time_series_errors.go
We're already exporting other processing errors, but ErrorInputFieldsWithoutRowsWideSeries is missing. We need to add it so some plugins can check for downstream processing errors that occur frequently and impact our success rate in some cases.
> Export `ErrorInputFieldsWithoutRowsWideSeries` error

- data/arrow.go
- data/arrow_test.go
This PR adds support for Arrow's `StringView` data type, which is needed for correct handling of string data received from datasources using the newer Arrow libraries and which often send string-typed fields as `StringView`.
**Which issue(s) this PR fixes**: N/A
This change is needed for implementing a data source plugin for modern arrow-based data sources if one tries to rely on Grafana Plugin SDK's own Arrow-to-Frame translation. Without this the implementors of data sources would need to reimplement the Arrow-to-Frame translation on their own in its entirety.
There might be other new Arrow data types that are not being handled in the Grafana Plugin SDK. This PR is intentionally narrowly focused on `StringView` …
> Add support for Arrow string view type

- data/frame.go
- data/frame_test.go
Fixes code that can cause crash in testing instead of a comparison test failure.
There's a bug in `data.FrameTestCompareOptions` that causes `Frame` comparison tests to crash when (for example) the compared frames have different number of rows and one of the columns is a `ConfFloat64`.
> fix: avoid crash due to fallthrough in *ConfFloat64 nil comparisons

- experimental/apis/data/v0alpha1/conversions.go
- experimental/apis/data/v0alpha1/conversions_test.go
fixes https://github.com/grafana/grafana-plugin-sdk-go/issues/1331
this new behavior is how this works in the current `/api/ds/query`.
technically this is a change in behavior, but it is in the `experimental` package, where such things are allowed.
> experimental: apis: do not default to refid=A
